# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if .Values.nats.stream_project_settings_events.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: {{ .Values.nats.stream_project_settings_events.name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.nats.stream_project_settings_events.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  name: {{ .Values.nats.stream_project_settings_events.name }}
  subjects:
  {{- range .Values.nats.stream_project_settings_events.subjects }}
    - {{ . }}
  {{- end }}
  storage: {{ .Values.nats.stream_project_settings_events.storage }}
  retention: {{ .Values.nats.stream_project_settings_events.retention }}
  maxAge: {{ .Values.nats.stream_project_settings_events.maxAge }}
  maxBytes: {{ .Values.nats.stream_project_settings_events.maxBytes }}
  maxMsgs: {{ .Values.nats.stream_project_settings_events.maxMsgs }}
  replicas: {{ .Values.nats.stream_project_settings_events.replicas }}
  compression: {{ .Values.nats.stream_project_settings_events.compression }}
  duplicateWindow: 2m
{{- end }}
